#!/bin/bash

flight_aws_s3_copy(){
  local opts=$1; shift

  local access_key=$(echo "$S3_KEY" | jq ".access" -r)
  local secret_key=$(echo "$S3_KEY" | jq ".secret" -r)

  local _ifs
  local info
  local kind
  local name
  local bucket
  local path
  local local_file

  _ifs=$IFS
  IFS=$'\n'
  for info in $(echo "$FLIGHT_DATA" | jq ".data[].properties" -c); do
    IFS=$_ifs

    kind=$(echo "$info" | jq ".kind" -r)
    name=$(echo "$info" | jq ".name" -r)
    bucket=$(echo "$info" | jq ".bucket" -r)

    _ifs=$IFS
    IFS=$'\n'
    for path in $(echo "$opts" | jq ".path[]" -c); do
      IFS=$_ifs

      local_file=$path/$name
      if [ -f "$local_file" ]; then
        s3cmd --access_key=$access_key --secret_key=$secret_key -q put "$local_file" "s3://$bucket/$kind/$path/$name"
      else
        >&2 echo "file not found: $local_file"
      fi
    done
  done

  echo $FLIGHT_DATA
}

action=$1; shift
flight_aws_s3_$action "$@"
